### ISSUE TITLE
AboutFloats Step6 `ValueLargerThanMaximumFloatThrows` doesn't work above .NET Core 2.2

### ISSUE THREAD

**Issue by dsschnau** [NotMyself/DotNetCoreKoans#100]
[Docs on Single.Parse here](https://docs.microsoft.com/en-us/dotnet/api/system.single.parse?view=netcore-3.1#System_Single_Parse_System_String_):

> 
>OverflowException
>
> .NET Framework and .NET **Core 2.2 and earlier versions only:** s represents a number less than MinValue or greater than MaxValue.

**Comment by SophieLemos** [comment]
#107

**Comment by NotMyself** [comment]
Resolved

**Comment by NotMyself** [comment]
@all-contributors please add @dsschnau for bug
