### ISSUE TITLE
Create a Logo for the Project

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#120]
It would be awesome to have a logo for the project that can be used in documentation. Something based on the original Ruby Koans [swirl logo](http://rubykoans.com/) would be awesome.

**Comment by jeannienguyen** [comment]
![DotNetCoreKoans](https://user-images.githubusercontent.com/44417397/94943899-489bc500-048d-11eb-9961-61c1957ead4d.png)

Hey, @NotMyself! I knocked something out real quick, let me know if it works! I'd love to contribute a PR to the repo.

**Comment by NotMyself** [comment]
Hi @jeannienguyen, thank you so much for looking at this issue. It looks like I did not describe what I wanted enough. The circle from ruby koans is the starting place I suggested. But this project is not a ruby project. it is based on [.net core](https://www.google.com/search?q=dotnet+core+logos&client=firefox-b-1-d&sxsrf=ALeKk00Mf4A0OpuwcGMFgRGvy1C4Qjlcaw:1601656802268&source=lnms&tbm=isch&sa=X&ved=2ahUKEwik-YDGrJbsAhWBnp4KHW8WDi0Q_AUoAXoECAwQAw&biw=1337&bih=875) and [c#](https://www.google.com/search?q=C%23+logos&tbm=isch&ved=2ahUKEwigs6rHrJbsAhWpgJ4KHaDFDo4Q2-cCegQIABAA&oq=C%23+logos&gs_lcp=CgNpbWcQAzIECAAQHjoECAAQQzoCCAA6BggAEAcQHlDvjwJYxJYCYJOgAmgAcAB4AIABRYgBhwGSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=5Vd3X-CsAqmB-gSgi7vwCA&bih=875&biw=1337&client=firefox-b-1-d).

**Comment by jeannienguyen** [comment]
@NotMyself What do you think about replacing the Ruby logo with a C# logo?

**Comment by NotMyself** [comment]
Sure let's see what that looks like.

**Comment by jeannienguyen** [comment]
![DotNetCoreKoans](https://user-images.githubusercontent.com/44417397/94948871-e777ef80-0494-11eb-9c37-15a25b26e93f.png)

Let me know what you think, @NotMyself!

**Comment by NotMyself** [comment]
This is a good option. Can I get an SVG version?

**Comment by NotMyself** [comment]
Also feel free to submit a PR with your logo ideas in a docs/images directory to the repo so you get your hacktoberfest credit.

**Comment by jeannienguyen** [comment]
Thanks, @NotMyself! I'll get an svg version to you soon along with the PR.

**Comment by Saishy** [comment]
Do you know if you can use the swirl or is it copyrighted?

**Comment by NotMyself** [comment]
@Saishy good question, I do not know.

**Comment by jeannienguyen** [comment]
@Saishy @NotMyself It's not, you can look up 'paint circles' and etc. It's actually a generic paint logo.

**Comment by NotMyself** [comment]
What do you two think about the logo being a zen master drawing the c# logo in the style of the paint circle? Is that too much? @Saishy @jeannienguyen

**Comment by Saishy** [comment]
I thought about the logo being the brush stroke in a hexagonal shape instead of a circle.

**Comment by jeannienguyen** [comment]
@Saishy Do you want to take it from here? I don't have the tools to design from scratch so I won't be able to make a hexagonal paint stroke.

**Comment by Saishy** [comment]
I also don't think I have anything good for that too...
I'm checking what I have but don't expect anything

**Comment by NotMyself** [comment]
Either way I greatly appreciate your help talking through it.

**Comment by jeannienguyen** [comment]
Hey, @NotMyself! I had to change it up a bit to be able to render an svg for you. I made a PR - let me know!

**Comment by NotMyself** [comment]
Thanks @jeannienguyen. I am going to leave the ticket over, so that other designers can find it and submit ideas during hacktoberfest. Then we can all pick the one we like best.
