### ISSUE TITLE
Could not load file or assembly Microsoft.DotNet.ProjectModel

### ISSUE THREAD

**Issue by arntj** [NotMyself/DotNetCoreKoans#13]
When trying to run this on Windows 10, it crashes. (And yes, I've installed, re-installed and re-re-installed .NET Core 1.0)

Console output:
```
C:\Dev\Git\DotNetCoreKoans>dotnet restore
log  : Restoring packages for C:\Dev\Git\DotNetCoreKoans\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in C:\Dev\Git\DotNetCoreKoans\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Dev\Git\DotNetCoreKoans\project.lock.json
log  : C:\Dev\Git\DotNetCoreKoans\project.json
log  : Restore completed in 2079ms.

C:\Dev\Git\DotNetCoreKoans>dotnet watch run
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.DotNet.Watcher.Tools.Program.<>c__DisplayClass3_0.<MainInternal>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Watcher.Tools.Program.MainInternal(String[] args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.Main(String[] args)
```

**Comment by NotMyself** [comment]
Thanks, I will take a look once I finish the refactoring work I am on now.

**Comment by NotMyself** [comment]
@arntj 

I committed my refactoring changes up to this point and ran the koans from my windows 10 vm. I seem to be running it fine. Could you try pulling latest and giving it another shot?

If it is still failing can you show me the output of `dotnet --info`?

This is what it looks like on my system:

```powershell
C:\src\DotNetCoreKoans [master ≡]> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
C:\src\DotNetCoreKoans [master ≡]>
```

**Comment by arntj** [comment]
Thanks for looking into this.

I'm absolutely sure I have the latest version of this repo. I tried deleting it and cloning it again just to make sure, still the same error. Seems like we have the exact same .net Core version, too. (Windows version is a bit different, but I don't think it should matter that much.)

```
C:\Dev\Git\DotNetCoreKoans>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by arntj** [comment]
The strange thing is that I actually seem to have Microsoft.DotNet.ProjectModel (1.0.0-rc3-003121), but it somehow doesn't get detected.

**Comment by NotMyself** [comment]
Try deleting the `project.lock.json` and running `dotnet restore` again. Does the newly generated file contain a reference to Microsoft.DotNet.ProjectModel?

**Comment by arntj** [comment]
Yes, it's referenced several places in the file.

**Comment by NotMyself** [comment]
Hrm.. Let's try forcing a redownload of everything. Run this in powershell `ren ~/.nuget/packages -newName 'packages.old'`, it will rename your local package cache and force the `dotnet restore` cli command to redownload everything into a new packages directory.

**Comment by arntj** [comment]
It works now. Thanks! :+1:

**Comment by NotMyself** [comment]
Thanks for working through the issue with me. You are the best!


![selfie-1](http://i.imgur.com/N7ydoVK.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
