### ISSUE TITLE
Question about NullIsNotAnObject

### ISSUE THREAD

**Issue by vgrigoriu** [NotMyself/DotNetCoreKoans#15]
What is the relevancy of this koan?

```cs
[Step(1)]
public void NullIsNotAnObject()
{
    Assert.True(typeof(object).IsAssignableFrom(null)); //not everything is an object
}
```

The parameter of `IsAssignableFrom` is of type `Type`, and it is [documented](https://msdn.microsoft.com/en-us/library/system.type.isassignablefrom(v=vs.110).aspx) that it returns false if the parameter is null. So this looks like an implementation detail of this function and not something generally true about objects or `null`. Am I missing something?

**Comment by NotMyself** [comment]
I believe this is a holdover from the Ruby Koans, which has an [AboutNil](https://github.com/edgecase/ruby_koans/blob/master/src/about_nil.rb#L4) koan demonstrating that Nil is an object in Ruby.

How would you modify this koan to make it more appropriate for c#?

**Comment by vgrigoriu** [comment]
Well, here are the relevant portions from the C# 4 specification, AFAICT:

> The special value `null` is compatible with all reference types and indicates the absence of an instance.

> An implicit conversion exists from the `null` literal to any nullable type.
> ... From the `null` literal to any _reference-type_.
> ... From the `null` literal to `T`, provided `T` is known to be a reference type.

> The result of the operation `E is T`, where `E` is an expression and `T` is a type, is [false] if `E` is a method group or the `null` literal, of if the type of `E` is a reference type or a nullable type and the value of `E` is `null`.

So maybe somthing like
```cs
Assert.False(null is object);
```
?

**Comment by NotMyself** [comment]
I like that. Make it so @vgrigoriu!
