### ISSUE TITLE
Add Koan about Dictionnary

### ISSUE THREAD

**Issue by Benjioe** [NotMyself/DotNetCoreKoans#154]
Add koan about [Dictionnary](https://docs.microsoft.com/fr-fr/dotnet/api/system.collections.generic.dictionary-2?view=netcore-3.1)

**Comment by jimmykurian** [comment]
@NotMyself , @Benjioe you can assign this issue to me.

**Comment by coder2213** [comment]
@NotMyself  @Benjioe 
Please review my [PR](https://github.com/NotMyself/DotNetCoreKoans/pull/162).
