### ISSUE TITLE
Missing EqualityAsserts.cs file

### ISSUE THREAD

**Issue by kilasuit** [NotMyself/DotNetCoreKoans#185]
Having been running through this the last few hours I keep getting 

```
Ponder the meaning in these lines:
EqualityAsserts.cs:line 96
EqualityAsserts.cs:line 63
```
or similar

However I can't seem to find where this file is at all

**Comment by MaxAtoms** [comment]
`EqualityAsserts.cs` and `BooleanAsserts.cs` are files from the test framework that we use.
It is called xUnit. These files provide methods like `Assert.True` and `Assert.Equal`.

You should see another line below the excerpt you sent. Is that the case?
It should start with `About`. That is the actual location of the Koan that you should be looking at.

I guess it would be easier to understand if we omit the paths from xUnit.
Therefore, I created issue #186.

**Comment by kilasuit** [comment]
Thanks as that makes sense now as much like the assert command is defined in the Pester PowerShell Module (similar to xUnit)

> You should see another line below the excerpt you sent. Is that the case?
It should start with About. That is the actual location of the Koan that you should be looking at.

Yeah I do & have been going through a few of them already.

>I guess it would be easier to understand if we omit the paths from xUnit.
Therefore, I created issue https://github.com/NotMyself/DotNetCoreKoans/issues/186.

Have commented on that issue :-)
