### ISSUE TITLE
AboutStrings date time and cultures

### ISSUE THREAD

**Issue by cmdkeen** [NotMyself/DotNetCoreKoans#21]
Really useful project!

In AboutStrings there's an issue with BuiltInDateFormaters and CustomDateFormaters for those of us outside the USA in that the date format is invalid. Changing to explicitly use the Invariant Culture resolves things.

```
DateTime.Parse("12/16/2011 2:35:02 PM", CultureInfo.InvariantCulture)
```

Perhaps a globalization koan might be worth adding ;)

**Comment by NotMyself** [comment]
@cmdkeen I like that idea a lot. Can I ask you to submit a pull request for the AboutStrings bug to make it clear?

I would also ask you to take a stab at adding a AboutGlobalization koan near the end of the path. That would be awesome. Thanks!

**Comment by NotMyself** [comment]
Good idea.
