### ISSUE TITLE
Semantic Question

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [NotMyself/DotNetCoreKoans#23]
So I built this thing and ran it and I'm getting this message in the console:

```
$ dotnet watch run
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 5428
Project DotNetCoreKoans (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
AboutAsserts AssertTruth has damaged your karma.
The Master says:
  You have not yet reached enlightenment.
[DotNetWatcher] fail: dotnet exit code: -1
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...

```
I did a debug and stepped through the whole thing and it appears as though it's running through several completely empty method blocks and eventually hitting a program exit of -1. So indeed, it was programmed to behave like this. My question is, what exactly is the intended purpose here?

**Comment by NotMyself** [comment]
You are correct, those methods are stubs for functionality that the original Ruby Koans had for output.

There is a little bit to unpack in the output of the application at this point:

1. The application is just a console application that exits 0 or -1 depending on if you have completed all the koans. If a koan is failing, it exits -1. If all koans pass, you win and it exits 0.

2. We are using [`dotnet watch`](https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.DotNet.Watcher.Tools), which watches your source code and anytime a file changes it reruns the application. This lets the student, run a `dotnet watch run` and then just edit Koan files watching the output in their console window.

3. dotnet watch puts these goofy DotNetWatcher messages in the output, there is a issue #1 filed to upgrade to the latest version when it is available that will allow us to suppress these messages.

4. The "application" simply walks down the koans as defined in the [path to enlightenment](/NotMyself/DotNetCoreKoans/blob/master/Koans/PathToEnlightenment.cs). It then executes each Step. If the step is successful, it executes the next step. It continues on till it hits a step that fails.

I am currently working on the Engine that does the walking and reporting. My goal is to get the output to look as much like the original Ruby Koans as I can.

The issues in this list are soliciting help in fleshing out the koans with good tutorials while I complete that work.

**Comment by TheOnlyRealTodd** [comment]
Awesome. Thanks so much for this, so basically, the student looks through the source files, completes them, and then when they're done, this little application will recognize that and change its output to 0 if I understand correctly. Meaning, the student must work through the different source files

**Comment by NotMyself** [comment]
Exactly.

**Comment by NotMyself** [comment]
Closing this issue.
