### ISSUE TITLE
What about Bitwise Operators and Shift Operators.

### ISSUE THREAD

**Issue by allenz0810** [NotMyself/DotNetCoreKoans#27]
for example  4 & 4 = ?, 4 | 4 = ?, 4^4 = ?, 4<<2 ? and 4 >>2?

**Comment by avjgit** [comment]
Real life, production usage example - state flags (Yes/No) for IsModified, HasWarnings, HasErrors.

**Comment by NotMyself** [comment]
Thanks for the PR.
