### ISSUE TITLE
Array.ForEach and Array.ConvertAll Missing

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#3]
The koans on Delegates and Lambdas are currently disabled because they depend on these two methods which were removed from Array. It looks like the [next release](dotnet-watch/issues/142) adds them back in.

**Comment by gregbair** [comment]
I think the correct issue for this is not the one you had, but [this one](/dotnet/corefx/issues/9998).

**Comment by NotMyself** [comment]
This was resolved a while back. Forgot to close the issue.
