### ISSUE TITLE
Better factoring of the console reporting

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#4]
Currently it is pretty janky. Maybe push reporting into the Koan base class and allow each koan to report their state to an interface.

**Comment by Dgaduin** [comment]
I can have a look at this if you want - what do you want to get out of the restructure?

**Comment by NotMyself** [comment]
@Dgaduin Thanks!

The Ruby Koans output looks like this:
![Screen Shot 2020-10-01 at 7 35 55 AM](https://user-images.githubusercontent.com/73120/94823493-c346e080-03b8-11eb-838b-a361daef282a.png)

Notice it is much more readable that this version. It does the following things:

- First message is which koan and test has failed
- The "Master" guides you on what exactly failed
- It guides you to the file and line that need to be corrected
- It keeps track of how far along the path you are

I am open to interpretation on this. I simply want the output to be better and guide the learner to the pit of success.

**Comment by Dgaduin** [comment]
Got you - let me try a few things and I'll drop some screenshots

**Comment by NotMyself** [comment]
Absolutely love it. We need to verify it works as expected on Windows, Linux and macOS. Why don't you set up a PR and I can test in linux and macOS.

**Comment by NotMyself** [comment]
Completed by @Dgaduin
