### ISSUE TITLE
"error NU1605: Detected package downgrade" for multiple packages

### ISSUE THREAD

**Issue by dutts** [NotMyself/DotNetCoreKoans#46]
From a clean clone of the repo, building on VS for Mac (7.2) reports the following packages as downgrades.

- System.Net.Primitives
- Microsoft.DotNet.Cli.Utils
- System.Net.Sockets
- System.Security.Principal

Cleaning Solution: DotNetCoreKoans (Debug)
Build started 16/10/2017 21:49:57.
__________________________________________________
Project "/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj" (Clean target(s)):

Target ReportAssetsLogMessages:
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605: Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Primitives (>= 4.0.11)
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605: Detected package downgrade: System.Security.Principal from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Security.Principal.Windows (>= 4.3.0) -> System.Security.Principal (>= 4.3.0) 
    /Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Security.Principal (>= 4.0.1)
    Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".
Done building target "ReportAssetsLogMessages" in project "DotNetCoreKoans.csproj" -- FAILED.

Done building project "DotNetCoreKoans.csproj" -- FAILED.

Build FAILED.

/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605: Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Primitives (>= 4.0.11)
/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605: Detected package downgrade: System.Security.Principal from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Net.Sockets (>= 4.1.0) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Security.Principal.Windows (>= 4.3.0) -> System.Security.Principal (>= 4.3.0) 
/Users/richard/Documents/Dev/DotNetCoreKoans/DotNetCoreKoans.csproj : error NU1605:  DotNetCoreKoans (>= 2.0.0) -> Microsoft.DotNet.Cli.Utils (>= 2.0.0) -> Microsoft.Build (>= 15.3.409) -> System.IO.Pipes (>= 4.0.0) -> System.Security.Principal (>= 4.0.1)
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.31

---------------------- Done ----------------------

Clean: 2 errors, 0 warnings

**Comment by NotMyself** [comment]
Hello World!

**Comment by dot4qu** [comment]
@dutts If you add NU1605 to the list of error codes not to warn for on line 6 of the DotNetCoreKoans.csproj file, it will build and run fine.

**Comment by NotMyself** [comment]
This should now be resolved.
