### ISSUE TITLE
Add Koan About Integers

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#6]
Add a koan called AboutIntegers that walks a new learner through the intricate details about `int` and `uint`.

**Comment by samqty** [comment]
Let me start with this one instead of the decimal

**Comment by NotMyself** [comment]
@samqty awesome I look forward to seeing what you come up with.

**Comment by tinymuledriver** [comment]
Is this one still open for contribution? If it is, I have something for a pull request. 

Thanks!
