### ISSUE TITLE
Step 29 in AboutGenericContainers Needs a Name

### ISSUE THREAD

**Issue by tomizechsterson** [NotMyself/DotNetCoreKoans#63]
It's just named "f" now, but what about something like "IteratingOverDictionary" or "AddingDataViaSubscript" or "DictionaryManipulation"?

**Comment by NotMyself** [comment]
Interesting, this came from the original koans by cory foy. I am not sure what this is demonstrating after looking at it. I am tempted to just remove it.

**Comment by tomizechsterson** [comment]
We could, but it appears to show that you can add an item to a dictionary simply by setting its value when accessing it via subscript. The second Assert, specifically, shows this. So, how about going with "AddingDataViaSubscript"?

**Comment by NotMyself** [comment]
Sure. That works for me.

**Comment by tomizechsterson** [comment]
Cool, PR incoming then :)
