### ISSUE TITLE
Add Koan About Constants

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#77]
The original ruby koans had a great koan [about constants](https://github.com/edgecase/ruby_koans/blob/master/src/about_constants.rb). What would that look like for C#?

**Comment by napalm684** [comment]
I would be willing to jump in on this if you could help me out a touch.  I am new to the `koan` concept.

**Comment by NotMyself** [comment]
@napalm684 awesome! I am happy to give you a quick explainer.

A Kōan is a story, dialogue, question, or statement which is used in Zen practice to provoke the "great doubt" and to practice or test a student's progress in Zen. The key here is practice and to learn by doing. So it is a fun play on a meditative practice to learn.

In most learning koan projects, this takes the form of a [set of failing unit tests](https://github.com/NotMyself/DotNetCoreKoans/tree/master/Koans). The student runs the program and each unit test is run until one fails. The a message is displayed describing the issue. The student must locate the test and fix it. 

This immediately gets the student in the unit testing mindset solving simple problems that can be verified programmatically. It also subtlety teaches them to read stack traces.

Koans typically start with an introduction to [asserts](https://github.com/NotMyself/DotNetCoreKoans/blob/master/Koans/AboutAsserts.cs), because the entire system hinges on knowing how they work. They then progress to basic types and complex types. More advanced koans will have the student build small logical applications.

Hints are usually in the form of comments directly in the unit test. They are written tongue in cheek as if a Zen master is guiding the learner.

So this issue links to the Ruby Koans koan on constants. C# also has constants, so it should be relatively easy to create a C# version. Here are some docs on [C# constants](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constants). The task is to understand the Ruby Koan, read the C# docs and create a new constants koan that covers the same things while highlighting what is different.

Any questions?

**Comment by napalm684** [comment]
Nope I will give it a stab.

**Comment by napalm684** [comment]
PR made https://github.com/NotMyself/DotNetCoreKoans/pull/104

**Comment by NotMyself** [comment]
Thanks!
