### ISSUE TITLE
Add Koan About Classes

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#78]
The original ruby koans had a great koan [about classes](https://github.com/edgecase/ruby_koans/blob/master/src/about_classes.rb). What would that look like for C#?

**Comment by NikiforovAll** [comment]
Hi, I would like to make a PR for this. Would you mind?

**Comment by NotMyself** [comment]
Sounds good to me. Thanks @NikiforovAll !
