### ISSUE TITLE
Add Koan About Iteration

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#80]
The original ruby koans had a great koan [about iteration](https://github.com/edgecase/ruby_koans/blob/master/src/about_iteration.rb). What would that look like for C#?

**Comment by SophieLemos** [comment]
I'd like to take this issue.

**Comment by NotMyself** [comment]
@SophieLemos all yours. Take a look at the Ruby Koan for some ideas. I think walking people through different loop types starting with a while loop, then for, then foreach is a good approach.

**Comment by SophieLemos** [comment]
Oh, I had assumed it was about implementing and using iterators but no problem.

**Comment by NotMyself** [comment]
Thank you!
