### ISSUE TITLE
Add Koan About Exceptions

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#81]
The original ruby koans had a great koan [about exceptions](https://github.com/edgecase/ruby_koans/blob/master/src/about_exceptions.rb). What would that look like for C#?

**Comment by A-Scratchy** [comment]
I'm really enjoying these. What a great concept!
I'm happy to take this one on if you like?

**Comment by NotMyself** [comment]
Thank you! Go for it @A-Scratchy!

**Comment by A-Scratchy** [comment]
Thanks @NotMyself 
Pull request created. #127
