### ISSUE TITLE
Add Dev Container support for VSCode and Codespaces

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#82]
To reach the maximum number of people who wish to learn C#, let's implement [development container support](https://code.visualstudio.com/docs/remote/containers) for this project. 

The end goal is a user being able to clone the repository, open it in vscode and have the Visual Studio Code [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension to provide them a development environment with no local installs.

The ultimate end game is learners can use GitHub[ Codespaces](https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces) to learn and have nothing installed on their machine.

**Comment by Benjioe** [comment]
Hello, 

Can I work on that one ? I know a little of docker.

**Comment by NotMyself** [comment]
@Benjioe Thanks!

Happy to have you take a look. Let me know if you have any questions.

**Comment by Benjioe** [comment]
Ok,

They are pré-config template for dotnet core who install  vs code extension :

**Comment by NotMyself** [comment]
@Benjioe agreed. I did some work around this this morning so I could get a code tour up and running. I think this ticket is resolved at this point. Do you see anything missing? Feel free to reopen if you do.

**Comment by Benjioe** [comment]
So, I don't need to make a PR ?
