### ISSUE TITLE
Add Automated Contributors Section to README.md

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#84]

**Comment by NotMyself** [comment]
@all-contributors please add @vgrigoriu  for code
@all-contributors please add @samqty  for code
@all-contributors please add @cmdkeen  for code
@all-contributors please add @delainewendling  for code
@all-contributors please add @allenz0810  for code
@all-contributors please add @beforan   for code
@all-contributors please add @LUS1N  for code
@all-contributors please add @euronay  for code
@all-contributors please add @dutts  for code
@all-contributors please add @melkor54248 for code
@all-contributors please add @agustashd for code
@all-contributors please add @OranguTech for code
@all-contributors please add @macleodmac for code
@all-contributors please add @pezholio  for code
@all-contributors please add @tomizechsterson for code
@all-contributors please add @codeman869 for code
@all-contributors please add @NauhcNoohc  for code

**Comment by NotMyself** [comment]
@all-contributors please add @vgrigoriu for code

**Comment by NotMyself** [comment]
@all-contributors please add @euronay for code

**Comment by NotMyself** [comment]
@all-contributors please add @samqty for code

**Comment by NotMyself** [comment]
@all-contributors please add @cmdkeen for code

**Comment by NotMyself** [comment]
@all-contributors please add @delainewendling for code

**Comment by NotMyself** [comment]
@all-contributors please add @allenz0810 for code

**Comment by NotMyself** [comment]
@all-contributors please add @beforan for code

**Comment by NotMyself** [comment]
@all-contributors please add @LUS1N for code

**Comment by NotMyself** [comment]
@all-contributors please add @dutts for code

**Comment by NotMyself** [comment]
@all-contributors please add @melkor54248 for code

**Comment by NotMyself** [comment]
@all-contributors please add @agustashd for code

**Comment by NotMyself** [comment]
@all-contributors please add @OranguTech for code

**Comment by NotMyself** [comment]
@all-contributors please add @macleodmac for code

**Comment by NotMyself** [comment]
@all-contributors please add @pezholio for code

**Comment by OranguTech** [comment]
Wow, next up a PR for the bot to recognize more than one contributor at a time!
