### ISSUE TITLE
Add Koan AboutDecimals

### ISSUE THREAD

**Issue by NotMyself** [NotMyself/DotNetCoreKoans#9]
This koan should be short and to the point.

Things to cover:
- Range
- Performance vs. Percision
- When to use it

**Comment by samqty** [comment]
started working on this

**Comment by TheOnlyRealTodd** [comment]
I'm interested in taking this on.

**Comment by NotMyself** [comment]
You can if you wish, I just ask that you not commit solution or project files. One of the goals of this project is it minimize the number of steps a new student has to take to begin writing code. Simply install the SDK, and a text editor and you are good to go.

**Comment by TheOnlyRealTodd** [comment]
@NotMyself Ok great. Actuallly, I got it up and running in VSC so it's all good, no project files.

**Comment by tomizechsterson** [comment]
Has this been addressed, or do we want to see some more steps in this koan?

**Comment by JoshuaBelden** [comment]
I see a koan for decimals in source. Is there additional work that needs to be completed before this issue is resolved?

**Comment by NotMyself** [comment]
Looks like I forgot to close it out.

**Comment by JoshuaBelden** [comment]
Dang! I was going for my first Hacktoberfest PR! :P That's ok, I'll find another one.
