### ISSUE TITLE
Line breaks in AboutStrings koan aren't consistent on windows with instructions

### ISSUE THREAD

**Issue by dsschnau** [NotMyself/DotNetCoreKoans#99]
Hi,

I'm giving these Koans a go and noticed a discrepancy. I'm running the koans on Windows 10.

My solution to `VerbatimStringsCanHandleMultipleLinesToo`:

```csharp
    [Step(6)]
    public void VerbatimStringsCanHandleMultipleLinesToo()
    {
      //Tip: What you create for the literal string will have to 
      //escape the newline characters. For Windows, that would be
      // \r\n. If you are on non-Windows, that would just be \n.
      //We'll show a different way next.
      var verbatimString = @"I
am a
broken line";

      // Make sure to use a literal string.
      // Escaped characters in verbatim strings are covered later.
      var literalString = "I\nam a\nbroken line";
      Assert.Equal(18, verbatimString.Length);
      Assert.Equal(literalString, verbatimString);
    }
```

In the `Tip:` bit, it says Windows line breaks are `\r\n`, and `\n` otherwise. But I'm running Windows, and I had to just use `\n` to solve the koan. Not sure if the fix here is to change the `Tip:` or something else.

**Comment by dsschnau** [comment]
Now I'm really befuddled. My solution to the next Koan, `ACrossPlatformWayToHandleStrings`, required use of `\r\n`.

```csharp
    [Step(7)]
    public void ACrossPlatformWayToHandleLineEndings()
    {
      //Since line endings are different on different platforms
      //(\r\n for Windows, \n for Linux) you shouldn't just type in
      //the hardcoded escape sequence. A much better way
      //(We'll handle concatenation and better ways of that in a bit)
      var literalString = "I" + System.Environment.NewLine + "am a" + System.Environment.NewLine + "broken line";
      var verbatimString = "I\r\nam a\r\nbroken line";
      Assert.Equal(literalString, verbatimString);
    }
```

**Comment by SophieLemos** [comment]
@dsschnau For practical purposes, most software will understand \n just fine on Windows.
For the verbatim string, you would want to do:
```csharp
		 var verbatimString = @"I
am a
broken line\n";
```
Keep in mind the indentation, that is intentional, because if you add a space within the string so it's indented, it will be included in the string.

Hope that helps.

**Comment by SophieLemos** [comment]
Looked into it further.
So this is a "fun" one. I had copied the same code onto a new console application, and they were checking out as equal.
It's related to the line ending the file uses.
If the source file is saved as CLRF, the code will work as expected.

**Comment by Dgaduin** [comment]
This might make it a bit more complicated, but there is also `System.Environment.NewLine`.

**Comment by dsschnau** [comment]
Nice, I verified this fixes (explains, really) things on my machine. With #124 including this info in the koan, I'll close this issue. Thanks @SophieLemos!
